# 共享配置模板
x-agent-bench-common: &agent-bench-common
  image: ${IMAGE_NAME:-code-cli-bench:v0.1.0}
  environment:
    - TZ=Asia/Shanghai
    - PYTHONPATH=/workspace/Pywen
    - ANTHROPIC_BASE_URL=${ANTHROPIC_BASE_URL:-}
    - ANTHROPIC_AUTH_TOKEN=${ANTHROPIC_AUTH_TOKEN:-}
    - QWEN_API_KEY=${QWEN_API_KEY:-}
    - QWEN_BASE_URL=${QWEN_BASE_URL:-}
    - QWEN_MODEL=${QWEN_MODEL:-}
    - QWEN_SERPER_API_KEY=${QWEN_SERPER_API_KEY:-}
    - PYWEN_TRAJECTORY_DIR=${PYWEN_TRAJECTORY_DIR:-}
    - CLAUDE_CODE_THEME=dark
  volumes:
    - ./tests:/workspace/Code-cli-bench/tests
    - ./output:/workspace/Code-cli-bench/output
    - agent-bench-data:/workspace/data
  working_dir: /workspace/Code-cli-bench
  tty: true
  stdin_open: true

services:
  bench-image:
    build: .
    image: ${IMAGE_NAME:-code-cli-bench:v0.1.0}
    command: ["bash", "-lc", "echo Built ${IMAGE_NAME:-code-cli-bench:v0.1.0}"]

  bench-headless:
    <<: *agent-bench-common
    container_name: bench-headless
    ports:
      - "${HOST_PORT:-8000}:8000"
    command: bash -lc "./run_headless.sh"
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  bench-interactive:
    <<: *agent-bench-common
    container_name: bench-interactive
    command: bash -lc "./run_interactive_tmux.sh"
    restart: unless-stopped

volumes:
  agent-bench-data:
    driver: local

